// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *LinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type StatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IP            string                 `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=UserAgent,proto3" json:"UserAgent,omitempty"`
	Time          string                 `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticsResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StatisticsResponse) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *StatisticsResponse) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *StatisticsResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type ListStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StatisticsResponse  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatisticsResponse) Reset() {
	*x = ListStatisticsResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatisticsResponse) ProtoMessage() {}

func (x *ListStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatisticsResponse.ProtoReflect.Descriptor instead.
func (*ListStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListStatisticsResponse) GetList() []*StatisticsResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type GetTotalClicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalClicks   int64                  `protobuf:"varint,1,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalClicksResponse) Reset() {
	*x = GetTotalClicksResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalClicksResponse) ProtoMessage() {}

func (x *GetTotalClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalClicksResponse.ProtoReflect.Descriptor instead.
func (*GetTotalClicksResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTotalClicksResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tanalytics\"\x1f\n" +
	"\vLinkRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"h\n" +
	"\x12StatisticsResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x0e\n" +
	"\x02IP\x18\x02 \x01(\tR\x02IP\x12\x1c\n" +
	"\tUserAgent\x18\x03 \x01(\tR\tUserAgent\x12\x12\n" +
	"\x04Time\x18\x04 \x01(\tR\x04Time\"K\n" +
	"\x16ListStatisticsResponse\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.analytics.StatisticsResponseR\x04list\";\n" +
	"\x16GetTotalClicksResponse\x12!\n" +
	"\ftotal_clicks\x18\x01 \x01(\x03R\vtotalClicks2\xaf\x01\n" +
	"\x10AnalyticsService\x12L\n" +
	"\rGetStatistics\x12\x16.analytics.LinkRequest\x1a!.analytics.ListStatisticsResponse\"\x00\x12M\n" +
	"\x0eGetTotalClicks\x12\x16.analytics.LinkRequest\x1a!.analytics.GetTotalClicksResponse\"\x00B&Z$AnalyticsService/internal/ports/grpcb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_proto_goTypes = []any{
	(*LinkRequest)(nil),            // 0: analytics.LinkRequest
	(*StatisticsResponse)(nil),     // 1: analytics.StatisticsResponse
	(*ListStatisticsResponse)(nil), // 2: analytics.ListStatisticsResponse
	(*GetTotalClicksResponse)(nil), // 3: analytics.GetTotalClicksResponse
}
var file_service_proto_depIdxs = []int32{
	1, // 0: analytics.ListStatisticsResponse.list:type_name -> analytics.StatisticsResponse
	0, // 1: analytics.AnalyticsService.GetStatistics:input_type -> analytics.LinkRequest
	0, // 2: analytics.AnalyticsService.GetTotalClicks:input_type -> analytics.LinkRequest
	2, // 3: analytics.AnalyticsService.GetStatistics:output_type -> analytics.ListStatisticsResponse
	3, // 4: analytics.AnalyticsService.GetTotalClicks:output_type -> analytics.GetTotalClicksResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
