version: '3.8'

services:
  analytics_postgres:
    container_name: analytics_postgres_container
    image: postgres:15
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5444:5432"
    networks:
      - analytics_net
    volumes:
      - analytics_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  analytics_pgadmin:
    container_name: analytics_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: analytics@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5150:5050" 
    networks:
      - analytics_net
    restart: unless-stopped

  analytics_zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182 
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182"
    networks:
      - analytics_net
    restart: unless-stopped

  analytics_kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - analytics_zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: analytics_zookeeper:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://analytics_kafka:9093,PLAINTEXT_HOST://localhost:29093 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - analytics_net
    restart: unless-stopped

networks:
  analytics_net:
    driver: bridge

volumes:
  analytics_pgdata:
