migrate-up:
	migrate -path internal/migrators -database "postgres://postgres:123@localhost:5433/postgres?sslmode=disable" up
migrate-down:
	migrate -path internal/migrators -database "postgres://postgres:123@localhost:5433/postgres?sslmode=disable" down